### ISSUE TITLE
Is anyone actively working on this?

### ISSUE THREAD

**Issue by Jascheminant-zz** [zortania/Darkside_New#8]
just wondering if anyone out there is actively working on this

**Comment by zortania** [comment]
Delra is when they get time. I can work on it sometimes, though a little too occupied to maintain it.

**Comment by Jascheminant-zz** [comment]
Just wanted to know if updates are being made and if there could be some additions added, I've been making slight tweaks for myself but not to your systems, just to my UI.

**Comment by Delra** [comment]
I am currently far too occupied to work on it or maintain it in any capacity, barring basic code overview. I will happily handle that, but I can't dig into Sunder, nor do I really want to until I regain some sanity. Feel free to open a pull request!
