### ISSUE TITLE
Def loop (shadowslip)

### ISSUE THREAD

**Issue by Delra** [zortania/Darkside_New#9]
Rury reported:
I'm syssin class and keep getting this....
[SND] [Resetting: def_shadowslip]

(shadowslip on)
H-6322/6322  M-4360/4360  E-29295/29295  W-18900/18900 (eb) XP-42.58% [none]
You are already slipping into the shadows when your victims fall.

(this continues ad nauseam, sunder not properly tracking that they have the shadowslip def)

**Comment by Galyleo** [comment]
I have had issues like this before, normally just looking at def fixes it, I'm assuming that it has something with darkside/sunder not tracking the defenses as they come up properly however for one reason or another.

**Comment by zortania** [comment]
It's also partly because it shares lines with a few other defs, so yeah,
just a quick glance at defs will usually fix most of them that have this
issue. There are definitely more than just this one.

**Comment by Galyleo** [comment]
Ah, I will see if I can figure something out to fix this, or at least fix the whole sharing lines thing.

**Comment by Delra** [comment]
Moving defenses over to GMCP would solve this problem unilaterally.

**Comment by zortania** [comment]
Yeah, just takes a big rebuild. I wouldn’t be able to get on that until the fall.

**Comment by Galyleo** [comment]
I'm working on a system that handles defenses using gmcp. Admittedly, I'm not the greatest at coding, but I'm at least putting forth the effort!
